#+TITLE: Notes on "Topoi" by Goldblatt
#+DATE: <2019-06-27 木>
#+AUTHOR: hisanobu-nakamura
#+EMAIL: 369bodhisattva@gmail.com
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:t p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: 
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export
#+LATEX_HEADER: \usepackage[margin=1.0in]{geometry}
#+LATEX_HEADER: \usepackage{tikz-cd}

* Chapter 3: Arrows instead of epsilons
** 3.1. Monic arrows
An arrow $f:a \rightarrow b$ in a category $\mathcal{C}$ is  /monic/ in $\mathcal{C}$ if for any pair $g,h:c \rightrightarrows a$ of $\mathcal{C}$ -arrows, equality $f\circ g = f \circ h$ implies that $g=h$.
The symbolism $f:a \rightarrowtail b$ is used to indicate that $f$ is monic.
*** 3.1. Exercise Solutions
In any category \\
(1) $g \circ f$ is monic if both $f$ and $g$ are monic.\\
(2) If $g \circ f$ is monic, then so is $f$.\\
*Solutions* \\
(1) \\
If $(g \circ f) \circ h_{1} = (g \circ f) \circ h_{2}$, then 
#+begin_export latex
\begin{eqnarray*}
(g \circ f) \circ h_{1} &=& (g \circ f) \circ h_{2}\\
g \circ (f \circ h_{1}) &=& g \circ (f \circ h_{2})\\
f \circ h_{1} &=& f \circ h_{2}  \quad (\because \text{g is monic})\\
h_{1} &=& h_{2}  \quad (\because \text{f is monic})
\end{eqnarray*}
#+end_export
Therefore, $(g \circ f)$ is monic. \\
(2) \\
If $f \circ h_{1} = f \circ h_{2}$, then 
#+begin_export latex
\begin{eqnarray*}
g \circ (f \circ h_{1}) &=& g \circ (f \circ h_{2})\\
(g \circ f) \circ h_{1} &=& (g \circ f) \circ h_{2}\\
h_{1} &=& h_{2}  \quad (\because \text{$f \circ g$ is monic})
\end{eqnarray*}
#+end_export
Hence, $f$ is monic.

** 3.2. Epic arrows
An arrow $f: a \rightarrow b$ is /epic/ (right-cancellable) in a category $\mathcal{C}$ if for any pair $g,h:b \rightrightarrows c$, the equality $g \circ f = h \circ f$ implies $g=h$ i.e. whenever a diagram
#+begin_export latex
\[ \begin{tikzcd}
a \arrow{r}{f} \arrow[swap]{d}{f} & b \arrow{d}{g} \\%
b \arrow{r}{h}& c
\end{tikzcd}
\]
#+end_export
commutes, then $g=h$. The notation $f:a \twoheadrightarrow b$ is used for epic arrows.

*** 3.2. Exercises(Duals of exercises in 3.1)
In any category\\
(1) $g \circ f$ is epic if both $f$ and $g$ are epic.\\
(2) If $g \circ f$ is epic, then so is $g$.\\
*Solutions* \\
(1) \\
Suppose that $f$ and $g$ are both epic, then if $h_{1} \circ (g \circ f) = h_{2} \circ (g \circ f)$,
#+begin_export latex
\begin{eqnarray*}
h_{1} \circ (g \circ f) &=& h_{2} \circ (g \circ f)\\
(h_{1} \circ g) \circ f &=& (h_{2} \circ g) \circ f\\
h_{1} \circ f &=& h_{2} \circ f\\
h_{1} &=& h_{2}.
\end{eqnarray*}
Hence, $g \circ f$ is epic.\\
#+end_export
(2)\\
Suppose $g \circ f$ is epic. Then, if $h_{1} \circ g = h_{2} \circ g$,
#+begin_export latex
\begin{eqnarray*}
(h_{1} \circ g) \circ f &=& (h_{2} \circ g) \circ f\\
h_{1} \circ (g \circ f) &=& h_{2} \circ (g \circ f)\\
h_{1} &=& h_{2}.
\end{eqnarray*}
#+end_export
Hence, $g$ is epic.
** 3.8 Products
*DEFINITION*
A product in a category $\mathcal{C}$ of two objects $a$ and $b$ is a $\mathcal{C}$ -object $a \times b$
together with a pair ($pr_{a}:a\times b \rightarrow a$, $pr_{b}:a\times b \rightarrow b$) of $\mathcal{C}$ -arrows such that for any pair of $\mathcal{C}$ -arrows of the form ($f:c \rightarrow a$, $g:c \rightarrow b$)
there is exactly one arrow $\langle a,g \rangle : c \rightarrow a \times b$ making
#+begin_export latex
\[ \begin{tikzcd}
                    && \arrow{lldd}[swap]{f} c \arrow[dashed]{dd}{\langle f,g\rangle} \arrow[rrdd,"g"]  && \\
		    &&&&\\
a  && \arrow{ll}[swap, near head]{pr_{a}} a \times b \arrow[rr, "pr_{b}"]&& b
\end{tikzcd}
\]
#+end_export
commute, i.e. such that  $pr_{a}\circ \langle f,g \rangle = f$, $pr_{b}\circ \langle f,g \rangle = g$. $\langle f,g \rangle$ is the product arrow of $f$ and $g$ with respect to the projections $pr_{a}$, $pr_{b}$.
